### ISSUE TITLE
[Enhancement/Feature] [Integration] [SonarQube] Filter Applications out when syncing Projects

### ISSUE THREAD

**Issue by PavelPikat** [port-labs/ocean#419]
### Motivation

Currently, SonarQube integration exports Applications when syncing Projects because it does not use qualifiers query string when talking to SonarQube API in its `get_components` method: https://github.com/port-labs/ocean/blob/main/integrations/sonarqube/client.py#L135

This results in Port displaying both Applications and Projects under Projects blueprint which is undesired.

### Proposed Changes

Use `qualifiers=TRK` filter/query string when talking to SonarQube API to fetch Projects to exclude Applications.
SonarQube API docs: https://next.sonarqube.com/sonarqube/web_api/api/components?query=components

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yairsimantov20** [comment]
Should work in the latest version 👍🏻
