### ISSUE TITLE
[Enhancement/Feature] [Integration] Linear

### ISSUE THREAD

**Issue by dash-aug** [port-labs/ocean#619]
### Motivation

We're using Linear for Issue / Project management and would like to use Port.

### Proposed Changes

Create a linear app plugin

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by MPTG94** [comment]
Hey @dash-aug!

An integration between Port and Linear is now available! You can access it from the data sources menu in the builder section of Port.

You can also check out the docs [here](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/linear/)
