### ISSUE TITLE
[Enhancement] [Integration] [Pager Duty] - Update raw data and default blueprints

### ISSUE THREAD

**Issue by danielsinai** [port-labs/ocean#76]
# Motivation

As for today, the Pager Duty integration initiated with data that lacks the main features of Pager Duty and people struggle to gain real value from it from the first installation. 

For improving that it would be best to enrich the `Raw Data` that the Pager Duty integration brings by addressing more Pager Duty APIS such as [Business Service](https://developer.pagerduty.com/api-reference/e67570b9d0e3d-list-business-services) and [Service Dependencies](https://developer.pagerduty.com/api-reference/b862ad9ead4d2-get-business-service-dependencies).

Moreover, to reduce the time, people gain value from the integration we would like to change the default resources of the integration to include more properties such as `Slack Channel`, `Maintenance window`, `Dependent services` and more.

# Proposed changes

1. Add a new kind of `Business Services` to bring data from the matching API.
2. Enrich the data on `Services` to include the dependencies of other services using the `Service Dependencies` API
3. Add a new kind of aggregatedIncidentData with the following data
```json
{
  "service_id": "PWER234D",
  "total_open_incidents": 12
}
```
4. Change the default blueprints to the following blueprints and update the config.yaml.
<details>
  <summary>Blueprints</summary>

  ```json
[
  {
    "identifier": "pagerdutyService",
    "description": "This blueprint represents a PagerDuty service in our software catalog",
    "title": "PagerDuty Service",
    "icon": "pagerduty",
    "schema": {
      "properties": {
        "description": {
          "icon": "Book",
          "type": "string",
          "title": "Description"
        },
        "status": {
          "icon": "pagerduty",
          "title": "Status",
          "type": "string",
          "enum": [
            "active",
            "warning",
            "critical",
            "maintenance",
            "disabled"
          ],
          "enumColors": {
            "active": "green",
            "warning": "yellow",
            "critical": "red",
            "maintenance": "turquoise",
            "disabled": "lightGray"
          }
        },
        "url": {
          "icon": "pagerduty",
          "title": "URL",
          "type": "string",
          "format": "url"
        },
        "oncall": {
          "icon": "TwoUsers",
          "title": "On Call",
          "type": "string",
          "format": "user"
        },
       "numberOfOpenIncidents": {
         "type": "number",
         "title": "Open Incidents"
        },
        "communication_channel": {
          "icon": "Slack",
          "title": "Communication Channel",
          "type": "string",
          "format": "url"
        },
        "maintenance_start_time": {
          "icon": "DevopsTool",
          "title": "Maintenance Start Time",
          "type": "string",
          "format": "date-time"
        },
        "maintenance_end_time": {
          "icon": "DevopsTool",
          "title": "Maintenance End Time",
          "type": "string",
          "format": "date-time"
        },
        "team": {
          "title": "Team",
          "type": "string",
          "icon": "DefaultProperty"
        },
        "last_incident": {
          "icon": "Clock",
          "title": "Last Incident",
          "type": "string",
          "format": "date-time"
        },
        "escalation_policy_unique_level": {
          "title": "Escalation Policy Unique Level",
          "type": "number",
          "icon": "DefaultProperty"
        }
      },
      "required": []
    },
    "mirrorProperties": {},
    "calculationProperties": {},
    "relations": {
      "uses": {
        "title": "Uses",
        "target": "pagerdutyService",
        "required": false,
        "many": true
      }
    }
  },
  {
    "identifier": "pagerdutyBusinessService",
    "description": "This blueprint represents a PagerDuty business service in our software catalog",
    "title": "PagerDuty Business Service",
    "icon": "pagerduty",
    "schema": {
      "properties": {
        "point_of_contact": {
          "icon": "TwoUsers",
          "type": "string",
          "title": "Point Of Contact",
          "format": "user"
        },
        "team": {
          "type": "string",
          "title": "Team",
          "icon": "DefaultProperty"
        },
        "description": {
          "type": "string",
          "title": "Description",
          "icon": "DefaultProperty"
        },
        "status_page": {
          "type": "string",
          "title": "Status Page",
          "format": "url",
          "icon": "DefaultProperty"
        }
      },
      "required": []
    },
    "mirrorProperties": {},
    "calculationProperties": {},
    "relations": {
      "services": {
        "title": "Services",
        "target": "pagerdutyService",
        "required": false,
        "many": true
      }
    }
  },
  {
    "identifier": "pagerdutyIncident",
    "description": "This blueprint represents a PagerDuty incident in our software catalog",
    "title": "PagerDuty Incident",
    "icon": "pagerduty",
    "schema": {
      "properties": {
        "status": {
          "icon": "DefaultProperty",
          "title": "Incident Status",
          "type": "string",
          "enum": [
            "triggered",
            "annotated",
            "acknowledged",
            "reassigned",
            "escalated",
            "reopened",
            "resolved"
          ],
          "enumColors": {
            "triggered": "red",
            "annotated": "red",
            "acknowledged": "green",
            "reassigned": "green",
            "escalated": "red",
            "reopened": "red",
            "resolved": "green"
          }
        },
        "url": {
          "type": "string",
          "format": "url",
          "title": "Incident URL",
          "icon": "DefaultProperty"
        },
        "urgency": {
          "icon": "Alert",
          "title": "Incident Urgency",
          "type": "string",
          "enum": [
            "high",
            "low"
          ],
          "enumColors": {
            "high": "lightGray",
            "low": "lightGray"
          }
        },
        "assignee": {
          "icon": "TwoUsers",
          "type": "string",
          "title": "Assignee",
          "format": "user"
        },
        "escalation_policy": {
          "icon": "BlankPage",
          "type": "string",
          "title": "Escalation Policy"
        },
        "created_at": {
          "icon": "DefaultProperty",
          "title": "Created At",
          "type": "string",
          "format": "date-time"
        },
        "updated_at": {
          "title": "Updated At",
          "type": "string",
          "format": "date-time",
          "icon": "DefaultProperty"
        }
      },
      "required": []
    },
    "mirrorProperties": {},
    "calculationProperties": {},
    "relations": {
      "pagerdutyService": {
        "title": "PagerDuty Service",
        "target": "pagerdutyService",
        "required": false,
        "many": false
      }
    }
  }
]
  ```
</details>

# Screenshots
<img width="1014" alt="image" src="https://github.com/port-labs/Port-Ocean/assets/51213812/04cde337-271e-4897-bfca-a394fd696aec">

**Comment by yonabogu** [comment]
Hi, totally agree :) 

I believe one of the main use-cases would involve generating scorecards that display the number of open incidents for a specific service. To achieve this in a user-friendly manner, we could enhance the existing implementation by introducing a new type of `aggregatedIncidentData`. This data would be associated with each individual Pager Duty Service and structured in JSON format as shown below:


```json
{
  "service_id": "PWER234D",
  "total_open_incidents": 12
}
``` 

Whenever a new incident is created or updated, this information would be automatically synchronized for the relevant service. Furthermore, during a resynchronization process, this aggregated incident data would also be included.

In addition, we could incorporate this functionality into the default blueprints by adding a property named numberOfOpenIncidents of type number to the PagerDutyService blueprint. This approach would provide a standardized way of representing and accessing the count of open incidents for each service.

**Comment by danielsinai** [comment]
> Hi, totally agree :)
> 
> I believe one of the main use-cases would involve generating scorecards that display the number of open incidents for a specific service. To achieve this in a user-friendly manner, we could enhance the existing implementation by introducing a new type of `aggregatedIncidentData`. This data would be associated with each individual Pager Duty Service and structured in JSON format as shown below:
> 
> ```json
> {
>   "service_id": "PWER234D",
>   "total_open_incidents": 12
> }
> ```
> 
> Whenever a new incident is created or updated, this information would be automatically synchronized for the relevant service. Furthermore, during a resynchronization process, this aggregated incident data would also be included.
> 
> In addition, we could incorporate this functionality into the default blueprints by adding a property named numberOfOpenIncidents of type number to the PagerDutyService blueprint. This approach would provide a standardized way of representing and accessing the count of open incidents for each service.

That's awesome, I will add that to the ehancement
