### ISSUE TITLE
[Bug] [deployment] [aws] Terrafrom module aws/ecs - aws_iam_role.task_execution_role is to long

### ISSUE THREAD

**Issue by erz4** [port-labs/ocean#830]
Hi all,

Encounter the next issue:

> Planning failed. Terraform encountered an error while generating this plan.
> 
> 
>  Error: expected length of name to be in the range (1 - 64), got ecs-task-execution-role-port-ocean-launchdarkly-launchdarkly_ocean
>  
>    with module.ocean_integration.module.port_ocean_ecs.aws_iam_role.task_execution_role,
>    on .terraform/modules/ocean_integration/deployment/terraform/aws/ecs/modules/ecs_service/main.tf line 130, in resource "aws_iam_role" "task_execution_role":
>   130:   name               = "ecs-task-execution-role-${local.service_name}"

that because:
https://github.com/port-labs/ocean/blob/cfffc9aa4fdacce88c75e268aa4f43af9101ae16/deployment/terraform/aws/ecs/modules/ecs_service/main.tf#L130
https://github.com/port-labs/ocean/blob/cfffc9aa4fdacce88c75e268aa4f43af9101ae16/deployment/terraform/aws/ecs/modules/ecs_service/main.tf#L2

I used the integration type `launchdarkly` and the identifier `launchdarkly_ocean` as our internal convention, which leads to a length of 66 while the maximum is 64.

**Comment by Tankilevitch** [comment]
Hey @erz4 👋 
we fixed the issue, please let me know if you experience anything else
