### ISSUE TITLE
Issues with pyjq 2.6.0 when installing on Windows

### ISSUE THREAD

**Issue by theagilepilot** [port-labs/ocean#839]
### Discussed in https://github.com/port-labs/ocean/discussions/837

<div type='discussions-op-text'>

<sup>Originally posted by **nicholasamato** July 23, 2024</sup>
I've been getting issues attempting to install ocean framework with a regular pip install and also with poetry.

The error always results when the install reachespyjq. I get the following error with poetry:

error: [WinError 2] The system cannot find the file specified

  at ~\pipx\venvs\poetry\Lib\site-packages\poetry\installation\chef.py:164 in _prepare
      160│
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│
      163│             if error is not None:
    → 164│                 raise error from None
      165│
      166│             return path
      167│
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pyjq (2.6.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "pyjq (==2.6.0)"'.

Does anyone have a solution? (Im using python 3.11.9)</div>

**Comment by yairsimantov20** [comment]
Can it be related to this issue? https://github.com/mwilliamson/jq.py/issues/20

**Comment by mwilliamson** [comment]
Hello! I'm the maintainer of jq.py. I just wanted to add that the original report was about pyjq, whereas the issue you've linked to is for jq.py, which is a separate project. In case it's of any help, jq.py has tentative support for Windows: specifically, there are currently wheels in a prerelease version, and, barring finding any issues, they should be included  in the next version.

**Comment by Tankilevitch** [comment]
Hey @theagilepilot 👋 
We just replaced our jq package from [pyjq](https://github.com/doloopwhile/pyjq) to [jq.py](https://github.com/mwilliamson/jq.py) this should come with more native windows support. 

Please let me know if it now works for you, closing for now feel free to re-open the issue.

Thank you @mwilliamson for jumping here 🙏
